// MCP Server Data - Second part (56-110)
const officialServersSecondPart = [
    // 56-75
    { id: 56, name: "Notion", description: "Connect with Notion workspaces", category: "API Integration" },
    { id: 57, name: "Obsidian", description: "Knowledge management with Obsidian", category: "File Operations" },
    { id: 58, name: "OpenAPI Schema", description: "Interactive exploration of OpenAPI specs", category: "Development" },
    { id: 59, name: "Oxylabs", description: "Scrape websites with Oxylabs Web API", category: "Web Automation" },
    { id: 60, name: "Perplexity", description: "Real-time web-wide research in conversational AI", category: "Web Automation" },
    { id: 61, name: "Pulumi", description: "Infrastructure as code operations", category: "Development" },
    { id: 62, name: "Puppeteer", description: "Browser automation and web scraping", category: "Web Automation" },
    { id: 63, name: "Qdrant", description: "Semantic memory layer on vector search engine", category: "Database Access" },
    { id: 64, name: "RazorPay", description: "Payment processing capabilities", category: "API Integration" },
    { id: 65, name: "Redis Cloud", description: "Cloud-hosted Redis service", category: "Database Access" },
    { id: 66, name: "Resend", description: "Email sending infrastructure", category: "API Integration" },
    { id: 67, name: "Riza", description: "Arbitrary code execution and tool-use platform", category: "Development" },
    { id: 68, name: "ScrapeGraph", description: "Web scraping with structured data extraction", category: "Web Automation" },
    { id: 69, name: "Search1API", description: "One API for Search, Crawling, and Sitemaps", category: "Web Automation" },
    { id: 70, name: "ScreenshotOne", description: "Render website screenshots", category: "Web Automation" },
    { id: 71, name: "Shopify", description: "E-commerce platform integration", category: "API Integration" },
    { id: 72, name: "Stripe", description: "Payment processing and financial services", category: "API Integration" },
    { id: 73, name: "Tavily", description: "AI-native search engine API", category: "Web Automation" },
    { id: 74, name: "Tembo", description: "PostgreSQL platform with AI capabilities", category: "Database Access" },
    { id: 75, name: "Unstructured", description: "Unstructured data processing workflows", category: "File Operations" },
    
    // 76-95
    { id: 76, name: "Webflow", description: "Website and CMS management", category: "API Integration" },
    { id: 77, name: "Wikipedia", description: "Search and retrieve content from Wikipedia", category: "Web Automation" },
    { id: 78, name: "Wolfram Alpha", description: "Computational knowledge engine", category: "AI Tools" },
    { id: 79, name: "YouTube Transcript", description: "Extract transcripts from YouTube videos", category: "Web Automation" },
    { id: 80, name: "ZenML", description: "MLOps and LLMOps pipelines", category: "AI Tools" },
    { id: 81, name: "Apify", description: "Use 3,000+ pre-built cloud tools to extract data from websites", category: "Web Automation" },
    { id: 82, name: "Audiense Insights", description: "Marketing insights and audience analysis", category: "API Integration" },
    { id: 83, name: "Axiom", description: "Query and analyze your Axiom logs, traces, and event data", category: "API Integration" },
    { id: 84, name: "Basic Memory", description: "Local-first knowledge management system", category: "AI Tools" },
    { id: 85, name: "Chronulus AI", description: "Predict anything with Chronulus AI forecasting", category: "AI Tools" },
    { id: 86, name: "CircleCI", description: "CI/CD platform integration", category: "Development" },
    { id: 87, name: "DataButton", description: "Build and deploy data products", category: "Development" },
    { id: 88, name: "DevHub CMS", description: "Content management system", category: "API Integration" },
    { id: 89, name: "Fibery", description: "Connected workspace for product companies", category: "API Integration" },
    { id: 90, name: "FlexPrice", description: "Intelligent pricing optimization", category: "API Integration" },
    { id: 91, name: "Gyazo", description: "Screenshot and image sharing", category: "File Operations" },
    { id: 92, name: "Hackle", description: "Feature management and experimentation", category: "Development" },
    { id: 93, name: "Handwriting OCR", description: "Optical character recognition for handwriting", category: "AI Tools" },
    { id: 94, name: "Husqvarna Automower", description: "Control robotic lawn mowers", category: "API Integration" },
    { id: 95, name: "HyperBrowser", description: "Browser automation and scraping", category: "Web Automation" },
    
    // 96-110
    { id: 96, name: "HyperSpell", description: "Advanced spell checking and text analysis", category: "AI Tools" },
    { id: 97, name: "Iaptic", description: "Analytics and optimization for in-app purchases", category: "API Integration" },
    { id: 98, name: "MultiversX", description: "Blockchain integration for Web3", category: "API Integration" },
    { id: 99, name: "Octomind", description: "Automated testing for web applications", category: "Development" },
    { id: 100, name: "Opik", description: "Visual content analysis and generation", category: "AI Tools" },
    { id: 101, name: "Pandoc", description: "Document format conversion", category: "File Operations" },
    { id: 102, name: "PIF", description: "Personal Intelligence Framework", category: "AI Tools" },
    { id: 103, name: "Pinecone", description: "Vector database for LLM applications", category: "Database Access" },
    { id: 104, name: "Placid.app", description: "Generate image and video creatives", category: "AI Tools" },
    { id: 105, name: "Postman", description: "Run Postman Collections via Newman", category: "Development" },
    { id: 106, name: "Productboard", description: "Product management platform", category: "API Integration" },
    { id: 107, name: "Ramp", description: "Spend management and analysis", category: "API Integration" },
    { id: 108, name: "Raygun", description: "Crash reporting and real user monitoring", category: "Development" },
    { id: 109, name: "Rember", description: "Create spaced repetition flashcards", category: "AI Tools" },
    { id: 110, name: "Vectorize", description: "Advanced retrieval and file extraction", category: "AI Tools" }
];