// MCP Server Data - First part (1-55)
const officialServers = [
    // 1-20
    { id: 1, name: "AWS KB Retrieval", description: "Retrieval from AWS Knowledge Base using Bedrock Agent Runtime", category: "API Integration" },
    { id: 2, name: "Azure ADX", description: "Query and analyze Azure Data Explorer databases", category: "Database Access" },
    { id: 3, name: "Brave Search", description: "Web and local search using Brave's Search API", category: "Web Automation" },
    { id: 4, name: "EverArt", description: "AI image generation using various models", category: "AI Tools" },
    { id: 5, name: "Everything", description: "Reference / test server with prompts, resources, and tools", category: "Development" },
    { id: 6, name: "Fetch", description: "Web content fetching and conversion for efficient LLM usage", category: "Web Automation" },
    { id: 7, name: "Filesystem", description: "Secure file operations with configurable access controls", category: "File Operations" },
    { id: 8, name: "Git", description: "Tools to read, search, and manipulate Git repositories", category: "Development" },
    { id: 9, name: "GitHub", description: "Repository management, file operations, and GitHub API integration", category: "API Integration" },
    { id: 10, name: "GitLab", description: "GitLab API, enabling project management", category: "API Integration" },
    { id: 11, name: "Google Drive", description: "File access and search capabilities for Google Drive", category: "File Operations" },
    { id: 12, name: "Google Maps", description: "Location services, directions, and place details", category: "API Integration" },
    { id: 13, name: "Memory", description: "Knowledge graph-based persistent memory system", category: "AI Tools" },
    { id: 14, name: "PostgreSQL", description: "Read-only database access with schema inspection", category: "Database Access" },
    { id: 15, name: "Playwright", description: "Browser automation and web scraping", category: "Web Automation" },
    { id: 16, name: "Redis", description: "Interact with Redis key-value stores", category: "Database Access" },
    { id: 17, name: "Sentry", description: "Retrieving and analyzing issues from Sentry.io", category: "API Integration" },
    { id: 18, name: "Sequential Thinking", description: "Dynamic and reflective problem-solving through thought sequences", category: "AI Tools" },
    { id: 19, name: "Slack", description: "Channel management and messaging capabilities", category: "API Integration" },
    { id: 20, name: "Sqlite", description: "Database interaction and business intelligence capabilities", category: "Database Access" },
    
    // 21-40
    { id: 21, name: "Time", description: "Time and timezone conversion capabilities", category: "Development" },
    { id: 22, name: "Airbnb", description: "Search Airbnb and get listing details", category: "API Integration" },
    { id: 23, name: "Airflow", description: "Connect to Apache Airflow using official python client", category: "API Integration" },
    { id: 24, name: "Aiven", description: "Navigate your Aiven projects and interact with services", category: "API Integration" },
    { id: 25, name: "AlphaVantage", description: "Stock market data API", category: "API Integration" },
    { id: 26, name: "BigQuery", description: "Inspect schemas and execute queries on BigQuery", category: "Database Access" },
    { id: 27, name: "BitRefill", description: "Buy gift cards and mobile refills with crypto", category: "API Integration" },
    { id: 28, name: "Box", description: "Intelligent Content Management platform", category: "File Operations" },
    { id: 29, name: "Chroma", description: "Embeddings, vector search, document storage, and full-text search", category: "Database Access" },
    { id: 30, name: "ClickHouse", description: "Query your ClickHouse database server", category: "Database Access" },
    { id: 31, name: "Cloudflare", description: "Deploy, configure & interrogate resources on the Cloudflare platform", category: "API Integration" },
    { id: 32, name: "Context7", description: "Interacting with the Context7 Security Knowledge Base", category: "API Integration" },
    { id: 33, name: "Deepseek", description: "Connect with DeepSeek's language models", category: "AI Tools" },
    { id: 34, name: "Descope", description: "Search audit logs and manage users", category: "API Integration" },
    { id: 35, name: "Discord", description: "Connect to Discord guilds through a bot", category: "API Integration" },
    { id: 36, name: "Docker", description: "Manage containers, images, volumes, and networks", category: "Development" },
    { id: 37, name: "Drupal", description: "Server for interacting with Drupal", category: "API Integration" },
    { id: 38, name: "DuckDuckGo", description: "Web search using DuckDuckGo", category: "Web Automation" },
    { id: 39, name: "Elevenlabs", description: "Text-to-speech with ElevenLabs API", category: "AI Tools" },
    { id: 40, name: "E2B", description: "Run code in sandboxed environments", category: "Development" },
    
    // 41-55
    { id: 41, name: "Elasticsearch", description: "MCP server implementation for Elasticsearch", category: "Database Access" },
    { id: 42, name: "Firecrawl", description: "Web scraping and crawling abilities", category: "Web Automation" },
    { id: 43, name: "Google Cloud", description: "Interact with Google Cloud services", category: "API Integration" },
    { id: 44, name: "Grafana", description: "Connect with Grafana metrics and dashboards", category: "API Integration" },
    { id: 45, name: "Heroku", description: "Manage Heroku applications and services", category: "API Integration" },
    { id: 46, name: "Home Assistant", description: "Control lights, switches, sensors, and more", category: "API Integration" },
    { id: 47, name: "JetBrains", description: "Interact with JetBrains IDEs", category: "Development" },
    { id: 48, name: "Kagisearch", description: "Web search using Kagisearch API", category: "Web Automation" },
    { id: 49, name: "Kong", description: "Manage API gateways", category: "API Integration" },
    { id: 50, name: "Kubernetes", description: "Manage Kubernetes clusters and resources", category: "Development" },
    { id: 51, name: "Linear", description: "Issue tracking and project management", category: "API Integration" },
    { id: 52, name: "MongoDB", description: "MongoDB database access and operations", category: "Database Access" },
    { id: 53, name: "MySQL", description: "MySQL database access and operations", category: "Database Access" },
    { id: 54, name: "Neo4j", description: "Graph database interactions", category: "Database Access" },
    { id: 55, name: "Neon", description: "Serverless Postgres database platform", category: "Database Access" }
];